export const reportsNames = {
  ALL_URLS: 'Indexed pages',
  CAMYASAB: 'Submitted and indexed',
  CAMYEyAE: 'Server error (5xx)',
  CAMYHyAE: 'Submitted URL not found (404)',
  CAMYHCAE: 'Submitted URL marked "noindex"',
  CAMYFCAE: 'Redirect error',
  CAMYICAE: 'Submitted URL seems to be a Soft 404',
  CAMYISAE: 'Submitted URL has crawl issue',
  CAMYGyAE: 'Submitted URL blocked by robots.txt',
  CAMYNSAE: 'Submitted URL returned 403',
  CAMYNiAE: 'Submitted URL blocked due to other 4xx issue',
  CAMYHiAE: 'Submitted URL returns unauthorised request (401)',
  CAMYBCAD: 'Indexed, though blocked by robots.txt',
  CAMYMiAD: 'Page indexed without content',
  CAMYByAC: 'Blocked by robots.txt',
  CAMYCCAC: 'Not Indexed by "noindex" tag',
  CAMYGCAC: 'Alternate page with proper canonical tag',
  CAMYFyAC: 'Crawled - currently not indexed',
  CAMYCyAC: 'Page with redirect',
  CAMYDSAC: 'Not found (404)',
  CAMYECAC: 'Duplicate, Google chose different canonical than user',
  CAMYDyAC: 'Duplicate without user-selected canonical',
  CAMYGSAC: 'Duplicate, submitted URL not selected as canonical',
  CAMYDiAC: 'Soft 404',
  CAMYFiAC: 'Discovered - currently not indexed',
  CAMYMyAC: 'Blocked due to access forbidden (403)',
  CAMYNCAC: 'Blocked due to other 4xx issue',
  CAMYCiAC: 'Blocked due to unauthorized request (401)',
  CAMYJyAC: 'Crawl anomaly',
};
